db-uri = "postgres://haf_admin@/haf_block_log"
db-schema = "reptracker_endpoints"
db-anon-role = "reptracker_user"
db-pool = 20
db-pool-acquisition-timeout = 10
db-extra-search-path = "reptracker_app"