rewrite ^/last-synced-block /rpc/get_rep_last_synced_block break;
# endpoint for get /last-synced-block

rewrite ^/version /rpc/get_reptracker_version break;
# endpoint for get /version

rewrite ^/accounts/([^/]+)/reputation /rpc/get_account_reputation?account-name=$1 break;
# endpoint for get /accounts/{account-name}/reputation

rewrite ^/$ / break;
# endpoint for openapi spec itself

rewrite ^/(.*)$ /rpc/$1 break;
# default endpoint for everything else
